name: ChatGlobo
version: 3.1
main: com.masitas.chatglobo.Main
api-version: 1.21
authors: [MasitasIA]
description: Muestra globos de texto automáticamente al chatear
commands:
  globo:
    description: Activa o desactiva tus propios globos
    usage: /globo
  globoglobal:
    description: Admin - Activa o desactiva el plugin para todos
    usage: /globoglobal
    permission: chatglobo.admin
  globoaltura:
    description: Admin - Ajusta la altura del globo
    usage: /globoaltura <numero>
    permission: chatglobo.admin
  globoclear:
    description: Admin - Limpia todos los globos activos
    usage: /globoclear
    permission: chatglobo.admin
  globomute:
    description: Admin - Silencia a un jugador para que no pueda usar globos
    usage: /globomute <jugador>
    permission: chatglobo.admin
  globotiempo:
    description: Admin - Ajusta el tiempo de duración de los globos
    usage: /globotiempo <segundos>
    permission: chatglobo.admin